/** @type {import('tailwindcss').Config} */

import { Screens } from "./src/constants/screens";

export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        screens: {
            xxs: `${Screens.XXS}px`,
            xs: `${Screens.XS}px`,
            s: `${Screens.S}px`,
            "karvi-s": `${Screens.KARVI_S}px`,
            sm: `${Screens.SM}px`,
            md: `${Screens.MD}px`,
            lg: `${Screens.LG}px`,
            xl: `${Screens.XL}px`,
            "karvi-xl": `${Screens.KARVI_XL}px`,
        },
        extend: {
            colors: {
                blue: {
                    100: "rgb(var(--blue-100))",
                    150: "rgb(var(--blue-150))",
                    250: "rgb(var(--blue-250))",
                    350: "rgb(var(--blue-350))",
                    500: "rgb(var(--blue-500))",
                    600: "rgb(var(--blue-600))",
                    700: "rgb(var(--blue-700))",
                    800: "rgb(var(--blue-800))",
                    1000: "rgb(var(--blue-1000))",
                },
                gray: {
                    100: "rgb(var(--gray-100))",
                    200: "rgb(var(--gray-200))",
                    350: "rgb(var(--gray-350))",
                    400: "rgb(var(--gray-400))",
                    500: "rgb(var(--gray-500))",
                    600: "rgb(var(--gray-600))",
                    700: "rgb(var(--gray-700))",
                    800: "rgb(var(--gray-800))",
                    900: "rgb(var(--gray-900))",
                    1000: "rgb(var(--gray-1000))",
                },
                orange: {
                    100: "rgb(var(--orange-100))",
                    200: "rgb(var(--orange-200))",
                    300: "rgb(var(--orange-300))",
                    400: "rgb(var(--orange-400))",
                    500: "rgb(var(--orange-500))",
                    600: "rgb(var(--orange-600))",
                    700: "rgb(var(--orange-700))",
                    800: "rgb(var(--orange-800))",
                    900: "rgb(var(--orange-900))",
                },
                green: {
                    100: "rgb(var(--green-100))",
                    200: "rgb(var(--green-200))",
                    300: "rgb(var(--green-300))",
                    500: "rgb(var(--green-500))",
                    600: "rgb(var(--green-600))",
                    700: "rgb(var(--green-700))",
                    800: "rgb(var(--green-800))",
                    900: "rgb(var(--green-900))",
                    950: "rgb(var(--green-950))",
                    1000: "rgb(var(--green-1000))",
                },
                yellow: {
                    200: "rgb(var(--yellow-200))",
                    300: "rgb(var(--yellow-300))",
                    400: "rgb(var(--yellow-400))",
                    500: "rgb(var(--yellow-500))",
                    600: "rgb(var(--yellow-600))",
                    700: "rgb(var(--yellow-700))",
                    800: "rgb(var(--yellow-800))",
                    900: "rgb(var(--yellow-900))",
                    950: "rgb(var(--yellow-950))",
                    1000: "rgb(var(--yellow-1000))",
                },
                red: {
                    100: "rgb(var(--red-100))",
                    200: "rgb(var(--red-200))",
                    300: "rgb(var(--red-300))",
                    400: "rgb(var(--red-400))",
                    500: "rgb(var(--red-500))",
                    600: "rgb(var(--red-600))",
                    700: "rgb(var(--red-700))",
                    800: "rgb(var(--red-800))",
                    900: "rgb(var(--red-900))",
                    1000: "rgb(var(--red-1000))",
                },
            },
        },
    },
    plugins: [],
};
